### ISSUE TITLE
Interface for LRS data

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/openchaussee#4]
# Goal

The main goal of this is to save linear referencing system (LRS) data in a postgres database. The data should be saved and edited as point data but it needs to offer an interface to import data from LRS and to query data in LRS format.

* Data is always saved as point data in a table inside the database.
* Have an interface to query a dedicated view with LRS data, calculated from point data
* Have an interface to import LRS data into point data

LRS data will not be saved directly inside the database!

# Import interface parameters (LRS)

* axe (foreign key to line data)
* reference point
* offset

# Point data

* axe (foreign key to line data)
* point geometry

# Triggers

* when the point geometry is modified, it will be snapped to the closest point on the corresponding axe, so the database enforces, that the point is always on the axe

# View

* An LRS view with
  * SELECT reads all the points and generates a LRS table
  * INSERT rule or trigger: create new points from LRS data
  * UPDATE possible but not available in an initial version

**Comment by signedav** [comment]
https://github.com/opengisch/openchaussee/commit/f6da467d48e634756b7b6674b6cd7a7f739559d0#comments

**Comment by signedav** [comment]
*Small Demo how it's now working*
![peek 2017-12-11 16-22](https://user-images.githubusercontent.com/28384354/33838354-a5052f42-de8f-11e7-94cd-54935179a779.gif)

**Comment by m-vaucher** [comment]
Thank's David, it work's perfectly!

**Comment by signedav** [comment]
This just came up - probably it's not relevant at all...

Could it be the case, that the user does not know where the start and where the end of the road is?

So he actually wants to enter from PR B +100 to PR C + 500 but selects as the first point the PR C and then the PR B?

At the moment it fails to save it like this. 
![openchausse_sacv](https://user-images.githubusercontent.com/28384354/34523940-e855941e-f099-11e7-98e2-9e3ef7f6a80f.gif)

Of course we could calculate it on the DB, that we use the lower PR as the start and the higher PR as the end of the geometry, but then the offsets go to wrong direction, I guess.

**Comment by m-kuhn** [comment]
@signedav can you open this as a new issue, so we don't forget about it and can either investigate (or close with a reason).
